# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72
api_version: 1
application: my-project-mikeapp
version: v1

handlers:
- url: /.*
  script: index.php

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/my-project-mikeapp:us-west2:mikedb;dbname=people_data
  MYSQL_USER: root
  MYSQL_PASSWORD: 'UnitySongRoot1'



# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php
